//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webIEA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCours
    {
        public TrainingCours()
        {
            this.MemberTranieeCommissions = new HashSet<MemberTranieeCommission>();
        }
    
        public int ID { get; set; }
        public string TrainingName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ValidatedHours { get; set; }
        public bool IsShow { get; set; }
        public int TypeID { get; set; }
        public string Languages { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public decimal Cost { get; set; }
        public bool IsFullTime { get; set; }
        public string Location { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime AddedOn { get; set; }
        public long AddedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual ICollection<MemberTranieeCommission> MemberTranieeCommissions { get; set; }
    }
}
