//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this custom property?.
        /// </summary>
        internal static string CustomProperty_DeleteConfirm {
            get {
                return ResourceManager.GetString("CustomProperty_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This custom property is linked to some objects. These values will be deleted together with the property definition whithout a possibility to restore. Do you want to do so?.
        /// </summary>
        internal static string CustomProperty_DeleteWithLinkedObjectsConfirm {
            get {
                return ResourceManager.GetString("CustomProperty_DeleteWithLinkedObjectsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document was found but you must authenticate yourself..
        /// </summary>
        internal static string Download_AuthenticationRequired {
            get {
                return ResourceManager.GetString("Download_AuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create request: {0}.
        /// </summary>
        internal static string Download_CantCreateRequest {
            get {
                return ResourceManager.GetString("Download_CantCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while processing the request: {0}.
        /// </summary>
        internal static string Download_ErrorThenProcessing {
            get {
                return ResourceManager.GetString("Download_ErrorThenProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;a href=&quot;{0}&quot;&gt;document&lt;/a&gt; you requested can not be downloaded from the link you used..
        /// </summary>
        internal static string Download_Failed {
            get {
                return ResourceManager.GetString("Download_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server replied: {0} {1}.
        /// </summary>
        internal static string Download_FailedReason {
            get {
                return ResourceManager.GetString("Download_FailedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the page returned.
        /// </summary>
        internal static string Download_HtmlReturned {
            get {
                return ResourceManager.GetString("Download_HtmlReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We searched your document on the following web sites:.
        /// </summary>
        internal static string Download_SitesSearched {
            get {
                return ResourceManager.GetString("Download_SitesSearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID parameter is wrong or not specified.
        /// </summary>
        internal static string Download_WrongID {
            get {
                return ResourceManager.GetString("Download_WrongID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder does not exist.
        /// </summary>
        internal static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy.
        /// </summary>
        internal static string Forms_CreateACopy {
            get {
                return ResourceManager.GetString("Forms_CreateACopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy of this template to edit it  and make a custom template..
        /// </summary>
        internal static string Forms_CreateACopyInfo {
            get {
                return ResourceManager.GetString("Forms_CreateACopyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Forms_EditTemplate {
            get {
                return ResourceManager.GetString("Forms_EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input fields.
        /// </summary>
        internal static string Forms_InputFields {
            get {
                return ResourceManager.GetString("Forms_InputFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Forms_Layout {
            get {
                return ResourceManager.GetString("Forms_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string Forms_Mandatory {
            get {
                return ResourceManager.GetString("Forms_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LogEntry_Date {
            get {
                return ResourceManager.GetString("LogEntry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s IP.
        /// </summary>
        internal static string LogEntry_IP {
            get {
                return ResourceManager.GetString("LogEntry_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log type.
        /// </summary>
        internal static string LogEntry_Type {
            get {
                return ResourceManager.GetString("LogEntry_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string LogEntry_Url {
            get {
                return ResourceManager.GetString("LogEntry_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referred Url.
        /// </summary>
        internal static string LogEntry_UrlReferrer {
            get {
                return ResourceManager.GetString("LogEntry_UrlReferrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LogEntry_UserName {
            get {
                return ResourceManager.GetString("LogEntry_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more:.
        /// </summary>
        internal static string MoreLanguages {
            get {
                return ResourceManager.GetString("MoreLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload the tree from the database.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use RSS icon of the Flexpage blocks to add items into RSS feed..
        /// </summary>
        internal static string RssManager_SubHeader {
            get {
                return ResourceManager.GetString("RssManager_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link to clipboard.
        /// </summary>
        internal static string RssManager_Tooltip {
            get {
                return ResourceManager.GetString("RssManager_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the files above and .
        /// </summary>
        internal static string ZipCheckAbove {
            get {
                return ResourceManager.GetString("ZipCheckAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the files below and .
        /// </summary>
        internal static string ZipCheckBelow {
            get {
                return ResourceManager.GetString("ZipCheckBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to download checked files in one archive.
        /// </summary>
        internal static string ZipDownload {
            get {
                return ResourceManager.GetString("ZipDownload", resourceCulture);
            }
        }
    }
}
